export interface District {
  districtId?: number;           // Auto-generated by backend
  censusDistrictCode: string;    // Unique, not updatable
  districtName: string;          // Required
  censusStateCode: string;       // FK to StatesMaster
  divisionCode: string;          // Required
  isActive: boolean;             // Default true
}
